/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsHeroRouteImport } from './routes/components/hero'
import { Route as ComponentsFloatingHeaderRouteImport } from './routes/components/floating-header'

const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsHeroRoute = ComponentsHeroRouteImport.update({
  id: '/components/hero',
  path: '/components/hero',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsFloatingHeaderRoute =
  ComponentsFloatingHeaderRouteImport.update({
    id: '/components/floating-header',
    path: '/components/floating-header',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/components/floating-header': typeof ComponentsFloatingHeaderRoute
  '/components/hero': typeof ComponentsHeroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/components/floating-header': typeof ComponentsFloatingHeaderRoute
  '/components/hero': typeof ComponentsHeroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/components/floating-header': typeof ComponentsFloatingHeaderRoute
  '/components/hero': typeof ComponentsHeroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo' | '/components/floating-header' | '/components/hero'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo' | '/components/floating-header' | '/components/hero'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/components/floating-header'
    | '/components/hero'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  ComponentsFloatingHeaderRoute: typeof ComponentsFloatingHeaderRoute
  ComponentsHeroRoute: typeof ComponentsHeroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/hero': {
      id: '/components/hero'
      path: '/components/hero'
      fullPath: '/components/hero'
      preLoaderRoute: typeof ComponentsHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/floating-header': {
      id: '/components/floating-header'
      path: '/components/floating-header'
      fullPath: '/components/floating-header'
      preLoaderRoute: typeof ComponentsFloatingHeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  ComponentsFloatingHeaderRoute: ComponentsFloatingHeaderRoute,
  ComponentsHeroRoute: ComponentsHeroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
